### ISSUE TITLE
Cache documents in server memory

### ISSUE THREAD

**Issue by timbl** [RubenVerborgh/solid-server-ts#4]
For speed, especially when many patches are made, he server should read the file into memory and keep it there for  a while,   writing out serialized versions whenever the data has been changed for more than a critical flush time.

Possibly, keep both triples store version and text (un parsed, serialized) version. 
- Stream the text to the net for a GET
- Stream the text to storage for the cache write back (following PUT/PASTE) 
- Parse the text to the triple store
- PATCH works on in the triple store
- Conflicts 409 are generated at the triple store between patches.

In this design, no one PUT or PASTE waits for the disk to be updated, it trusts  the system
and a server crash during the flush time loses data.

**Comment by RubenVerborgh** [comment]
We could implement this through a Decorator pattern. The memory cache would implement the [`IResourceStore` interface](https://github.com/RubenVerborgh/solid-server-ts/blob/c2a533c831582fae152c0c3a36fa12b98944f2e0/src/ldp/ResourceStore.ts), and take another `IResourceStore` as constructor argument.
