### ISSUE TITLE
Add HttpHandler and HttpServer interfaces

### ISSUE THREAD

**Issue by michielbdejong** [RubenVerborgh/solid-server-ts#8]
https://rubenverborgh.github.io/solid-server-architecture/solid-architecture-v1-2-0.pdf describes HttpHandler and HttpServer interfaces, but they're missing from this repo.

**Comment by RubenVerborgh** [comment]
solid-server-ts was never intended to be an implementation of solid-arch; it was the inspiration for solid-arch.

Can this be handled at the inrupt repo? Probably best to break the fork link with this repo.
