### ISSUE TITLE
LdpOperation does not implement Operation interface correctly

### ISSUE THREAD

**Issue by michielbdejong** [RubenVerborgh/solid-server-ts#9]
It has `requiredPermission: PermissionSet` and `target: ResourceIdentifier`, but `body` instead of `requestBody`, and no `preferences` or `execute`.

**Comment by michielbdejong** [comment]
(comparing it to https://rubenverborgh.github.io/solid-server-architecture/solid-architecture-v1-2-0.pdf)

**Comment by RubenVerborgh** [comment]
solid-server-ts is not an implementation of solid-arch; can this be handled at the inrupt repo?
